import { Language, WeatherModelKey, WeatherTheme } from './types';

export const weatherModels: Array<{
  key: WeatherModelKey;
  apiName: string;
  label: string;
  countryCode: string;
  color: string;
  nameAr: string;
  nameEn: string;
  forecastDays: number;
}> = [
  {
    key: 'ecmwf',
    apiName: 'ecmwf_ifs',
    label: 'ECMWF',
    countryCode: 'EU',
    color: '#64d8ff',
    nameAr: 'الأوروبي',
    nameEn: 'European',
    forecastDays: 15
  },
  {
    key: 'gfs',
    apiName: 'gfs_seamless',
    label: 'GFS',
    countryCode: 'US',
    color: '#63f2bb',
    nameAr: 'الأمريكي',
    nameEn: 'American',
    forecastDays: 16
  },
  {
    key: 'icon',
    apiName: 'icon_seamless',
    label: 'ICON',
    countryCode: 'DE',
    color: '#c5a3ff',
    nameAr: 'الألماني',
    nameEn: 'German',
    forecastDays: 7.5
  },
  {
    key: 'gem',
    apiName: 'gem_global',
    label: 'GEM',
    countryCode: 'CA',
    color: '#ffba70',
    nameAr: 'الكندي',
    nameEn: 'Canadian',
    forecastDays: 10
  },
  {
    key: 'jma',
    apiName: 'jma_gsm',
    label: 'JMA',
    countryCode: 'JP',
    color: '#ff7fa8',
    nameAr: 'الياباني',
    nameEn: 'Japanese',
    forecastDays: 11
  }
];

const weatherDescriptions: Record<number, { ar: string; en: string }> = {
  0: { ar: 'سماء صافية', en: 'Clear sky' },
  1: { ar: 'صحو غالبًا', en: 'Mainly clear' },
  2: { ar: 'غائم جزئيًا', en: 'Partly cloudy' },
  3: { ar: 'غائم كليًا', en: 'Overcast' },
  45: { ar: 'ضباب', en: 'Fog' },
  48: { ar: 'ضباب متجمد', en: 'Freezing fog' },
  51: { ar: 'رذاذ خفيف', en: 'Light drizzle' },
  53: { ar: 'رذاذ متوسط', en: 'Moderate drizzle' },
  55: { ar: 'رذاذ كثيف', en: 'Dense drizzle' },
  56: { ar: 'رذاذ متجمد خفيف', en: 'Freezing drizzle' },
  57: { ar: 'رذاذ متجمد كثيف', en: 'Dense freezing drizzle' },
  61: { ar: 'مطر خفيف', en: 'Light rain' },
  63: { ar: 'مطر متوسط', en: 'Moderate rain' },
  65: { ar: 'مطر غزير', en: 'Heavy rain' },
  66: { ar: 'مطر متجمد', en: 'Freezing rain' },
  67: { ar: 'مطر متجمد غزير', en: 'Heavy freezing rain' },
  71: { ar: 'ثلج خفيف', en: 'Light snow' },
  73: { ar: 'ثلج متوسط', en: 'Moderate snow' },
  75: { ar: 'ثلج غزير', en: 'Heavy snow' },
  77: { ar: 'حبيبات ثلج', en: 'Snow grains' },
  80: { ar: 'زخات مطر خفيفة', en: 'Light showers' },
  81: { ar: 'زخات مطر متوسطة', en: 'Moderate showers' },
  82: { ar: 'زخات مطر قوية', en: 'Heavy showers' },
  85: { ar: 'زخات ثلج خفيفة', en: 'Light snow showers' },
  86: { ar: 'زخات ثلج كثيفة', en: 'Heavy snow showers' },
  95: { ar: 'عاصفة رعدية', en: 'Thunderstorm' },
  96: { ar: 'عاصفة مع برد خفيف', en: 'Thunderstorm with hail' },
  99: { ar: 'عاصفة مع برد كثيف', en: 'Severe hail storm' }
};

export const getWeatherDescription = (code: number, language: Language = 'ar') =>
  weatherDescriptions[code]?.[language] ??
  (language === 'ar' ? 'حالة غير معروفة' : 'Unknown condition');

export function getWeatherTheme(code: number, isDay = true): WeatherTheme {
  if (!isDay && code <= 3) return 'night';
  if ([95, 96, 99].includes(code)) return 'storm';
  if ([71, 73, 75, 77, 85, 86].includes(code)) return 'snow';
  if ([45, 48].includes(code)) return 'fog';
  if ([51, 53, 55, 56, 57, 61, 63, 65, 66, 67, 80, 81, 82].includes(code)) return 'rain';
  if ([2, 3].includes(code)) return 'cloudy';
  return 'clear';
}

export function convertWeatherApiCode(code: number): number {
  const mapping: Record<number, number> = {
    1000: 0, 1003: 2, 1006: 3, 1009: 3, 1030: 45, 1063: 61,
    1066: 71, 1069: 66, 1072: 66, 1087: 95, 1114: 75, 1117: 86,
    1135: 45, 1147: 45, 1150: 51, 1153: 53, 1168: 66, 1171: 67,
    1180: 61, 1183: 61, 1186: 63, 1189: 63, 1192: 65, 1195: 65,
    1201: 67, 1204: 66, 1207: 67, 1210: 71, 1213: 71, 1216: 73,
    1219: 73, 1222: 75, 1225: 75, 1237: 77, 1240: 80, 1243: 81,
    1246: 82, 1249: 85, 1252: 86, 1255: 85, 1258: 86, 1261: 77,
    1264: 77, 1273: 95, 1276: 95, 1279: 96, 1282: 99
  };
  return mapping[code] ?? 0;
}

export const translations = {
  ar: {
    brand: 'مرصد الطقس',
    tagline: 'طقسك الآن، وتوقعات أدق ..... من عدة نماذج عالمية',
    search: 'ابحث عن مدينة بالعربية أو الإنجليزية',
    location: 'موقعي',
    overview: 'الطقس الآن',
    searchAction: 'بحث',
    coordinateHint: 'يمكنك أيضًا لصق الإحداثيات',
    locating: 'جارٍ تحديد موقعك',
    coordinatesLocation: 'موقع محدد بالإحداثيات',
    blend: 'تجميع النماذج',
    forecastSource: 'مصدر التوقعات',
    observationSource: 'الرصد الحالي',
    todayForecastSource: 'توقع اليوم',
    smartOutlook: 'الملخص الحسابي الذكي',
    outlookDescription: 'قراءة آلية محسوبة من بيانات المصدر المختار وليست تنبؤًا مولدًا أو تحذيرًا رسميًا',
    oneDay: 'يوم واحد',
    threeDays: 'ثلاثة أيام',
    sevenDays: 'سبعة أيام',
    confidence: 'درجة الاتفاق',
    confidenceSingle: 'نموذج منفرد',
    confidenceHigh: 'مرتفعة',
    confidenceMedium: 'متوسطة',
    confidenceLow: 'منخفضة',
    supportingData: 'بيانات مساندة',
    modelUnavailable: 'خارج مدة هذا النموذج',
    weatherMap: 'خريطة الطقس',
    mapTagline: 'استكشف الطقس عالميًا واختر أي نقطة',
    flatMap: 'خريطة مسطحة',
    globe: 'كرة أرضية',
    layers: 'طبقات الخريطة',
    radar: 'رادار الأمطار',
    satellite: 'الأقمار الصناعية',
    dustLayer: 'الغبار والهباء الجوي',
    cyclones: 'الأعاصير المدارية',
    selectOnMap: 'اضغط على أي نقطة لعرض توقعاتها',
    mapLoading: 'نجهز طبقات الخريطة العالمية',
    mapUnavailable: 'تعذر تحميل الخريطة الآن',
    liveLocation: 'موقعي المباشر',
    mapCredits: 'مصادر الخريطة',
    hideMapCredits: 'إخفاء المصادر',
    customComparison: 'مقارنة مخصصة',
    customBlend: 'تجميع مخصص',
    commonPeriod: 'الفترة المشتركة فقط',
    fullPeriod: 'كامل المدة',
    selectAll: 'اختيار الكل',
    clearSelection: 'إلغاء الاختيار',
    apply: 'تطبيق',
    participatingModels: 'النماذج المشاركة',
    hourly: 'الساعات القادمة',
    daily: 'الأيام القادمة',
    models: 'مقارنة النماذج',
    details: 'تفاصيل الطقس',
    feels: 'المحسوسة',
    high: 'العظمى',
    low: 'الصغرى',
    rain: 'الأمطار',
    humidity: 'الرطوبة',
    wind: 'الرياح',
    gusts: 'الهبات',
    visibility: 'مدى الرؤية',
    pressure: 'الضغط',
    clouds: 'الغيوم',
    uv: 'الأشعة فوق البنفسجية',
    sunrise: 'الشروق',
    sunset: 'الغروب',
    updated: 'آخر تحديث',
    today: 'اليوم',
    showAll: 'عرض الأيام الستة عشر',
    showLess: 'عرض عشرة أيام',
    sources: 'حالة مصادر البيانات',
    available: 'متاح',
    unavailable: 'غير متاح',
    share: 'مشاركة',
    copy: 'نسخ الملخص',
    favorite: 'إضافة للمفضلة',
    removeFavorite: 'إزالة من المفضلة',
    settings: 'الإعدادات',
    recent: 'عمليات البحث الأخيرة',
    favorites: 'المدن المفضلة',
    noResults: 'لم نعثر على مدينة مطابقة',
    loading: 'نجمع أحدث التوقعات من النماذج العالمية',
    error: 'تعذر جلب بيانات الطقس الآن',
    retry: 'إعادة المحاولة',
    useCached: 'نعرض آخر بيانات محفوظة على جهازك',
    install: 'تثبيت التطبيق',
    modelAgreement: 'توافق النماذج',
    modelNote: 'المؤشر توضيحي ويعتمد على مقدار اختلاف درجات الحرارة بين النماذج',
    maxTemperature: 'درجات الحرارة العظمى',
    precipitation: 'كميات الأمطار',
    close: 'إغلاق',
    hourlyDetails: 'تفاصيل الساعات',
    noAlerts: 'لا توجد مؤشرات جوية شديدة حاليًا',
    developer: 'تصميم وتطوير محمد جعفر الشوحة',
    localTime: 'الوقت المحلي',
    copied: 'تم نسخ الملخص',
    downloaded: 'تم تجهيز بطاقة الطقس',
    dataSources: 'بيانات من عدة مصادر عالمية'
  },
  en: {
    brand: 'Weather Observatory',
    tagline: 'Your weather now, with sharper forecasts ..... from global models',
    search: 'Search for a city in Arabic or English',
    location: 'My location',
    overview: 'Weather now',
    searchAction: 'Search',
    coordinateHint: 'You can also paste coordinates',
    locating: 'Locating you',
    coordinatesLocation: 'Location by coordinates',
    blend: 'Model blend',
    forecastSource: 'Forecast source',
    observationSource: 'Current observation',
    todayForecastSource: "Today's forecast",
    smartOutlook: 'Calculated smart outlook',
    outlookDescription: 'An automated reading calculated from the selected source; it is not generated advice or an official warning',
    oneDay: 'One day',
    threeDays: 'Three days',
    sevenDays: 'Seven days',
    confidence: 'Agreement level',
    confidenceSingle: 'Single model',
    confidenceHigh: 'High',
    confidenceMedium: 'Medium',
    confidenceLow: 'Low',
    supportingData: 'Supporting data',
    modelUnavailable: 'Outside this model range',
    weatherMap: 'Weather map',
    mapTagline: 'Explore global weather and select any point',
    flatMap: 'Flat map',
    globe: 'Globe',
    layers: 'Map layers',
    radar: 'Rain radar',
    satellite: 'Satellite',
    dustLayer: 'Dust and aerosols',
    cyclones: 'Tropical cyclones',
    selectOnMap: 'Tap anywhere to view its forecast',
    mapLoading: 'Preparing global weather layers',
    mapUnavailable: 'The map is unavailable right now',
    liveLocation: 'Live location',
    mapCredits: 'Map sources',
    hideMapCredits: 'Hide sources',
    customComparison: 'Custom comparison',
    customBlend: 'Custom blend',
    commonPeriod: 'Common period only',
    fullPeriod: 'Full range',
    selectAll: 'Select all',
    clearSelection: 'Clear selection',
    apply: 'Apply',
    participatingModels: 'Participating models',
    hourly: 'Next hours',
    daily: 'Daily forecast',
    models: 'Model comparison',
    details: 'Weather details',
    feels: 'Feels like',
    high: 'High',
    low: 'Low',
    rain: 'Rain',
    humidity: 'Humidity',
    wind: 'Wind',
    gusts: 'Gusts',
    visibility: 'Visibility',
    pressure: 'Pressure',
    clouds: 'Clouds',
    uv: 'UV index',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    updated: 'Updated',
    today: 'Today',
    showAll: 'Show all 16 days',
    showLess: 'Show 10 days',
    sources: 'Data source status',
    available: 'Available',
    unavailable: 'Unavailable',
    share: 'Share',
    copy: 'Copy summary',
    favorite: 'Add favorite',
    removeFavorite: 'Remove favorite',
    settings: 'Settings',
    recent: 'Recent searches',
    favorites: 'Favorite cities',
    noResults: 'No matching city found',
    loading: 'Collecting the latest global forecasts',
    error: 'Weather data is unavailable right now',
    retry: 'Try again',
    useCached: 'Showing the latest data saved on your device',
    install: 'Install app',
    modelAgreement: 'Model agreement',
    modelNote: 'This indicator is illustrative and based on temperature spread between models',
    maxTemperature: 'Maximum temperatures',
    precipitation: 'Precipitation',
    close: 'Close',
    hourlyDetails: 'Hourly details',
    noAlerts: 'No severe weather signals right now',
    developer: 'Designed and developed by Mohammed Jafer Alshouha',
    localTime: 'Local time',
    copied: 'Summary copied',
    downloaded: 'Weather card is ready',
    dataSources: 'Data from multiple global sources'
  }
} as const;
